# Use a base image with Java 8 installed
FROM openjdk:8-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY devschool-front-app-server/build/libs/devschool-front-app-server-1.0.0.jar .

# Expose port 8081
EXPOSE 8081

# Specify the command to run your application
CMD ["java", "-jar", "devschool-front-app-server-1.0.0.jar"]
